branch-defaults:
  default:
    environment: Testsampleapp-env
  master:
    environment: Testsampleapp-env
environment-defaults:
  Testsampleapp-env:
    branch: null
    repository: null
deploy:
  artifact: E:\webprojects\arahansa\build\libs\arahansa-0.0.1-SNAPSHOT.jar
global:
  application_name: TestSampleApp
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Java 8 running
    on 64bit Amazon Linux/2.5.2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
